name: Run Tests on Modified Directories

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Find and Run Tests
        run: |
          declare -A dir_tested=()
          for file in ${{ steps.changed-files.outputs.all_changed_files }}
          do
            # Get the directory and check if there is a corresponding spec file
            dir=$(dirname $file)
            if [[ ! ${dir_tested[$dir]} ]]; then
              spec_file="$dir/*spec*"
              if [ -f $spec_file ]; then
                # If a spec file exists, run the test
                echo "Running tests for $spec_file"
                npx jest $spec_file
                dir_tested[$dir]=true
              fi
            fi
          done