name: Run Tests on Modified Directories

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Find and Run Tests
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}
          do
            # ファイル名を出力
            echo "File changed: $file"
            # ディレクトリを取得し、対応するspecファイルがあるか確認
            dir=$(dirname $file)
            spec_file="$dir/*spec*"
            if [ -f $spec_file ]; then
              # specファイルが存在する場合、テストを実行
              echo "Running tests for $spec_file"
              npx jest $spec_file
            fi
          done